// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR6FTJiNQkunUjjesv6oBiGrLmLKPmIpA',
    appId: '1:1092115205073:web:2ef224928a51e130b46ef0',
    messagingSenderId: '1092115205073',
    projectId: 'stadium-booking-854aa',
    authDomain: 'stadium-booking-854aa.firebaseapp.com',
    storageBucket: 'stadium-booking-854aa.appspot.com',
    measurementId: 'G-VHNP168F1J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTfik6uMgK_XBbrPL8rsQB5GnVal4wFVg',
    appId: '1:1092115205073:android:285d439df787fbfab46ef0',
    messagingSenderId: '1092115205073',
    projectId: 'stadium-booking-854aa',
    storageBucket: 'stadium-booking-854aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP2zJYR8p42VPpEfy7IneK7JmfCCds3xs',
    appId: '1:1092115205073:ios:1c180771a5929075b46ef0',
    messagingSenderId: '1092115205073',
    projectId: 'stadium-booking-854aa',
    storageBucket: 'stadium-booking-854aa.appspot.com',
    androidClientId: '1092115205073-oqrlq3u281nfjblg7udgsvqh17cti6eu.apps.googleusercontent.com',
    iosClientId: '1092115205073-kgigipadesfs1hd24cs8lvu96u9f4j0q.apps.googleusercontent.com',
    iosBundleId: 'com.example.clientApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBP2zJYR8p42VPpEfy7IneK7JmfCCds3xs',
    appId: '1:1092115205073:ios:96eee8c1e569c18fb46ef0',
    messagingSenderId: '1092115205073',
    projectId: 'stadium-booking-854aa',
    storageBucket: 'stadium-booking-854aa.appspot.com',
    androidClientId: '1092115205073-oqrlq3u281nfjblg7udgsvqh17cti6eu.apps.googleusercontent.com',
    iosClientId: '1092115205073-pl69luse0kupphjg29k4vr6m83gchqmo.apps.googleusercontent.com',
    iosBundleId: 'com.example.clientApp.RunnerTests',
  );
}
